### ISSUE TITLE
Requests for data creates duplicates

### ISSUE THREAD

**Issue by LucasKantola** [AlexGustafsson/systembolaget-api#12]
# When running a command for assortment thru cli it creates a large mulitple of the same values in the json output

Running any release thru cli starts to duplicate data and doesnt stop when the results outnumber the totalresults 

### When canceling the command using ctrl+c
```
{"time":"2024-06-09T01:06:37.3209814+02:00","level":"ERROR","msg":"Failed to fetch next item","error":"context canceled","results":42660,"resultsLimit":0,"totalResults":25052}
context canceled
```

**Comment by AlexGustafsson** [comment]
See #9. The API seems to start returning duplicates after a rather large amount of entries.

**Comment by AlexGustafsson** [comment]
Closing as duplicate.

**Comment by AlexGustafsson** [comment]
This issue seems to have been solved. New builds available in the latest release. See #9.
