### ISSUE TITLE
availability in which stores and stock level?

### ISSUE THREAD

**Issue by killernils** [AlexGustafsson/systembolaget-api#19]
Hi! Im playing around with you awesome tool and trying to figure out if I can query which stores a specific product is available in, and how many?

**Comment by AlexGustafsson** [comment]
Yes and no. There's an open pull request to add support for getting the current stock balance of a product.

See #15.

**Comment by killernils** [comment]
> Yes and no. There's an open pull request to add support for getting the current stock balance of a product.
> 
> See #15.

sorry, Missed that one, will go through it, thanks!
