### ISSUE TITLE
failed to get API key

### ISSUE THREAD

**Issue by AlbinLindskog** [AlexGustafsson/systembolaget-api#8]
Any command fails with:

`{"level":"error","time":"2022-10-31T15:47:03+01:00","caller":"systembolaget/credentials.go:106","msg":"Unable to find script path","stacktrace":"github.com/alexgustafsson/systembolaget-api/v2/systembolaget.getAppSettingsScriptPath\n\t/Users/alexgustafsson/Documents/GitHub/systembolaget-api/systembolaget/credentials.go:106\ngithub.com/alexgustafsson/systembolaget-api/v2/systembolaget.getAppSettings\n\t/Users/alexgustafsson/Documents/GitHub/systembolaget-api/systembolaget/credentials.go:42\ngithub.com/alexgustafsson/systembolaget-api/v2/systembolaget.GetAPIKey\n\t/Users/alexgustafsson/Documents/GitHub/systembolaget-api/systembolaget/credentials.go:21\nmain.getAPIKey\n\t/Users/alexgustafsson/Documents/GitHub/systembolaget-api/cmd/common.go:33\nmain.ActionAssortment\n\t/Users/alexgustafsson/Documents/GitHub/systembolaget-api/cmd/assortment.go:57\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/Users/alexgustafsson/go/pkg/mod/github.com/urfave/cli/v2@v2.11.2/command.go:173\ngithub.com/urfave/cli/v2.(*App).RunContext\n\t/Users/alexgustafsson/go/pkg/mod/github.com/urfave/cli/v2@v2.11.2/app.go:382\ngithub.com/urfave/cli/v2.(*App).Run\n\t/Users/alexgustafsson/go/pkg/mod/github.com/urfave/cli/v2@v2.11.2/app.go:251\nmain.main\n\t/Users/alexgustafsson/Documents/GitHub/systembolaget-api/cmd/main.go:215\nruntime.main\n\t/usr/local/Cellar/go/1.19/libexec/src/runtime/proc.go:250"}
failed to get API key, please specify one`

Looks like Systembolaget have changed their site, so you're no longer able to readily get an API-key. Unfortunately I don't know how it used to work. I'll update if I figure anything out, but it'll probably be easier for me to write a new scraper than to wrap my head around their previous implementation.

**Comment by AlbinLindskog** [comment]
I ended up pulling all the info I wanted from https://www.systembolaget.se/api/gateway/productsearch/search/.
It has the same functionality, but doesn't require any API-keys. Just a 'baseURL: https://api-extern.systembolaget.se/sb-api-ecommerce/v1' header.

**Comment by dunderrrrrr** [comment]
Hi, Albin. 

Does this method still work? Im getting a 401 error when sending `GET` requests to https://www.systembolaget.se/api/gateway/productsearch/search/ with set `baseUrl` header. 

Been trying to scrape `/sortiment` with selenium for a couple of days but its...  finicky, to say the least. 

Regards,

**Comment by AlbinLindskog** [comment]
> Hi, Albin.
> 
> Does this method still work? Im getting a 401 error when sending `GET` requests to https://www.systembolaget.se/api/gateway/productsearch/search/ with set `baseUrl` header.
> 
> ```
> * Preparing request to https://www.systembolaget.se/api/gateway/productsearch/search/?page=1&size=30&sortBy=Score&sortDirection=Ascending&categoryLevel1=%C3%96l
> * Current time is 2023-01-04T18:32:29.559Z
> ...
> > GET /api/gateway/productsearch/search/?page=1&size=30&sortBy=Score&sortDirection=Ascending&categoryLevel1=%C3%96l HTTP/2
> > Host: www.systembolaget.se
> > user-agent: insomnia/2021.7.2
> > baseurl: https://api-extern.systembolaget.se/sb-api-ecommerce/v1
> > accept: */*
> 
> < HTTP/2 401 
> ```
> 
> Been trying to scrape `/sortiment` with selenium for a couple of days but its... finicky, to say the least.
> 
> Regards,

It looks like they've changed the baseURL.

`curl 'https://www.systembolaget.se/api/gateway/productsearch/search/' -H 'baseURL: https://api-systembolaget.azure-api.net/sb-api-ecommerce/v1' ` 

works now.

**Comment by AlbinLindskog** [comment]
> did you manage to solve this issue with the script or did you go your own way @AlbinLindskog ?

I went my own way; a simple for loop that steps through all the pages on the url above and dumps the response into a .json file. Neither pretty nor robust, but I only needed to pull the data once, so it's good enough.

**Comment by moffepoffe** [comment]
@AlbinLindskog is this something you want to share? :D

**Comment by AlbinLindskog** [comment]
> @AlbinLindskog is this something you want to share? :D

Yeah, sure. It's not much to share though.

`import json
import requests
from time import sleep

data = []
headers = {
    'baseURL': 'https://api-systembolaget.azure-api.net/sb-api-ecommerce/v1',
	'User-Agent': 'curl/7.54.0', # No idea why the default'python-requests/2.28.2' doesn't work. Bad scraping protection?
}

try:
  for i in range(0, 1000):
	response = requests.get(f'https://www.systembolaget.se/api/gateway/productsearch/search/?page={i}', headers=headers)
	data.extend(response.json()['products'])
	sleep(1)
finally:
  with open('data.json', 'w', encoding='utf-8') as file:
      json.dump(data, file, ensure_ascii=False, indent=4)`

**Comment by moffepoffe** [comment]
@AlbinLindskog  Many thanks I really appreciate it!

**Comment by sandberghannes** [comment]
@AlbinLindskog Did they change the baserurl again?

**Comment by AlbinLindskog** [comment]
> @AlbinLindskog Did they change the baserurl again?

Yep, looks like it. They're using a 'Ocp-Apim-Subscription-Key'-header now instead.

`curl 'https://api-extern.systembolaget.se/sb-api-ecommerce/v1/productsearch/search?page=1' -H 'Ocp-Apim-Subscription-Key: cfc702aed3094c86b92d6d4ff7a54c84'`

I don't know how long it's valid for, but you can get a new one simply by inspecting the network traffic when you make a search query in your browser on their site.
